create table sc_arya.t_address (add_id int4 generated by default as identity, address_type varchar(255), city varchar(255), primary key (add_id));
create table sc_arya.t_dept (dept_code int4 generated by default as identity, count int4, dept_name varchar(255), primary key (dept_code));
create table sc_arya.t_studentone (code int4 generated by default as identity, name varchar(255), address_add_id int4, dept int4 not null, primary key (code));
alter table if exists sc_arya.t_studentone add constraint FKg04pi6w49evy2fh6qc9pdymsr foreign key (address_add_id) references sc_arya.t_address;
alter table if exists sc_arya.t_studentone add constraint FK5tlptmikqucdfsv86km7cyhyv foreign key (dept) references sc_arya.t_dept;
